### ISSUE TITLE
Comparison with existing alternatives

### ISSUE THREAD

**Issue by Alexander--** [SimonVT/schematic#15]
It would be nice to hear pros and cons of Schematic, compared to existing projects, such as [ProviGen](https://github.com/TimotheeJeannin/ProviGen) and [AnnotatedSQL](https://github.com/hamsterksu/Android-AnnotatedSQL).

**Comment by SimonVT** [comment]
I wont be writing a comparison. It'd probably be kind of biased anyway. I'd like to know if any of you decide to do it tho.
