### ISSUE TITLE
schematicOutPackage parameter ignored

### ISSUE THREAD

**Issue by kubotron** [SimonVT/schematic#21]
The 0.6.0 version of Schematic seems to work fine, but it ignores the schematicOutPackage parameter and generates the classes in build.{buildtype}.{the.usual.application.package}.generated instead. Is this the intended behaviour? Regards, Jakub

**Comment by geovanisouza92** [comment]
Yes, [it seems](https://github.com/SimonVT/schematic/commit/df63c790aa2af829d4b906bf7fb2013a620196e8).

**Comment by kubotron** [comment]
Oh ok, thanks. I Missed that one. It works if I set the correct name ( {the.usual.application.package}.generated )in the AndroidManifest.xml

**Comment by SimonVT** [comment]
Yes, I removed schematicOutPackage. There's a packageName on the Database and Provider annotation now.
I'll make sure to create a changelog one of these days :)
