### ISSUE TITLE
Can we have "ON CONFLICT UPDATE" annotation ?

### ISSUE THREAD

**Issue by kubotron** [SimonVT/schematic#23]
Schematic is pretty awesome! It would be really cool if it would support specifying the "ON CONFLICT ..." policy for the "@Unique"-annotated fields. Thanks for the awesomeness!

**Comment by nizig** [comment]
+1

**Comment by danielbeutel** [comment]
That would be great to have
+1

**Comment by jush** [comment]
I've created a pull request for that feature. See https://github.com/SimonVT/schematic/pull/24. Hopefully it gets merged.

**Comment by danielbeutel** [comment]
Any chance this will get merged?

**Comment by SimonVT** [comment]
Version 0.6.1 has been released with #24.
