### ISSUE TITLE
There is no way to clean and recreate database

### ISSUE THREAD

**Issue by nguyentruongtho** [SimonVT/schematic#25]
It is quite often that we need to reset the data base instead of manually update it.

Currently the method annotated with `@OnUpgrade` is unable to call `onCreate` method from generated Provider (actually we can reference the generated class and call that `onCreate` method but we will have some little issue with the compiler).

What I would like to do is something as follow:

```java
  @OnCreate public static void onCreateDatabaseComplete(Context context, SQLiteDatabase db) {
  }

  @OnUpgrade public static void onUpgrade(Context context, SQLiteDatabase db, int oldVersion,
      int newVersion) {
    db.execSQL("DROP TABLE IF EXISTS test");
   // RECREATE database schema, or somehow call `onCreate` here
 }
```

Is there any workaround for this?

**Comment by SimonVT** [comment]
You can call onCreate on the generated SQLiteOpenHelper class.
GeneratedDatabase.getInstance(context).onCreate(db);

**Comment by nguyentruongtho** [comment]
This is exactly what I did, and it has problem with the compiler (Android Studio) on rebuild. 
![image](https://cloud.githubusercontent.com/assets/1457567/7674018/8e29529c-fd48-11e4-8034-72e0a7d2c876.png).

**Comment by SimonVT** [comment]
I doubt this is an issue with Schematic, so I'm closing it. Schematic just generates the classes, which should happen before the project is compiled. Either way, I can't control in what order those happen.
