### ISSUE TITLE
Support for Foreign keys

### ISSUE THREAD

**Issue by LouisCo** [SimonVT/schematic#26]
Hi !
If you still support the library, could you add an @**ForeignKey** annotation ?

Thanks
Best regards

**Comment by geovanisouza92** [comment]
@LouisCo It already [have](https://github.com/SimonVT/schematic/blob/master/schematic-annotations/src/main/java/net/simonvt/schematic/annotation/References.java).

But you need to set the [```PRAGMA foreign_keys = ON;```](https://www.sqlite.org/foreignkeys.html#fk_enable) in ```@OnCreate```, I believe.

**Comment by LouisCo** [comment]
Thank you for your hint.
Is not foreign keys enabled by default in android ? I already used foreign key in an SQLite Content Provider and I never had to execute this sql command ?

**Comment by geovanisouza92** [comment]
@LouisCo As far I knew, it isn't. To ensure, just download a database file from one of your apps and open it on SQLite Manager, for example:

```sh
$ adb -d shell "run-as <YOUR APP PACKAGE> cat /data/data/<YOUR APP PACKAGE>/databases/<DATABASE FILE NAME> > /sdcard/<DATABASE FILE NAME>"

$ adb pull "/sdcard/<DATABASE FILE NAME>"
```

In my case, ![references exists](http://i.imgur.com/Ypj4aXI.png), but ![it's not enabled](http://i.imgur.com/Jb27iB0.png)

**Comment by LouisCo** [comment]
So if you tried to delete a row referencing another table's row, it wouldn't throw any exception… Thank you !

**Comment by LouisCo** [comment]
I just have to put the **PRAGMA foreign_keys = ON;** in a String annotated with @**ExecOnCreate** to enable foreign keys, and @**References** works as expected ! Thanks !

**Comment by geovanisouza92** [comment]
Nice!
