### ISSUE TITLE
Using the same columns declaration for multiple tables

### ISSUE THREAD

**Issue by tehmou** [SimonVT/schematic#31]
It would seem it is not possible to use the same interface for multiple tables in the same database.

    @Table(JsonIdColumns.class) public static final String GITHUB_REPOSITORIES = "repositories";
    @Table(JsonIdColumns.class) public static final String USER_SETTINGS = "userSettings";

Yields me an error:

    Error:Execution failed for task ':app:_compileDebugJava'.
    > java.lang.IllegalArgumentException: com.tehmou.rxbookapp.data.schematicProvider.JsonIdColumns

If I create a new interface for each table and extend the same base class it works. I would suggest either show a more meaningful error, or enable using the same column declarations for multiple tables.

**Comment by SimonVT** [comment]
Fixed by ad5435a :)
