### ISSUE TITLE
blob query with InexactContentUti

### ISSUE THREAD

**Issue by tasomaniac** [SimonVT/schematic#37]
I have a BLOB column in my database that I use it to store boolean values. 

`ContentValues` class accepts true/false as a direct parameter and stores them as 1 and 0 in the database. When I query normally, I have to like this `WHERE PREFERRED=1`. When I use `selectionArgs` and send `new String[] {"1"}` it returns an empty `Cursor`. 

The same thing is happening to the below query. I sends "1" as the parameter using `selectionsArgs` and the result is always empty. 

```
        @InexactContentUri(
                name = "OPENWITH_PREFERRED",
                path = OpenWithDatabase.OPENWITH + "/preferred/#",
                type = "vnd.android.cursor.fir/openwith",
                whereColumn = PREFERRED,
                pathSegment = 2)
        public static Uri preferred(long id) {
            return Uri.withAppendedPath(CONTENT_URI, "preferred/1");
        }
```

At the end, I couldn't find any way to query boolean columns using `@InexactContentUri`

I hope I will be understood. I don't know if this is a bug or not. I just wanted you to know it.

**Comment by SimonVT** [comment]
So if you query the database yourself it doesn't work either?

**Comment by tasomaniac** [comment]
It works in the classic way when I query the dB with contentresolver. But
InexactContentUri is cool to use.

**Comment by tasomaniac** [comment]
I just wanted to see your opinion.

**Comment by SimonVT** [comment]
Well, for your example I wouldn't use `@InexactContentUri`, I'd just use `@ContentUri` and define the where parameter.

**Comment by tasomaniac** [comment]
Oh I thought there can be only a single @ContentUri in a class. I couldn't
annotate a method with it. And your sample project as well has only one.

Can I just add another @ContentUri?

**Comment by SimonVT** [comment]
Sure, you can have all the `@ContentUri` annotated fields you want :)

**Comment by tasomaniac** [comment]
Do they have to be fields? Not methods?

**Comment by SimonVT** [comment]
Yes, the `@ContentUri` Uri never changes, so that's just for static fields. `@InexactContentUri` is used when the Uri is created based on some value (e.g. an id).

**Comment by tasomaniac** [comment]
It seems that I can do what I need using `@ContentUri`. 
`@IntexactContentUri` with blobs do not work. If it is ok, we can close this issue.

**Comment by SimonVT** [comment]
`@InexactContentUri` works fine with blobs, your `@InexactContentUri` and `@ContentUri` just aren't querying the same thing. If you care you can attach a debugger and find out what is being passed to `SQLiteDatabase#query` in the two cases, to see what the difference it.

**Comment by tasomaniac** [comment]
Yes it did. Thank you very much. 

Little bit documentation on `@InexactContentUri` and `@ContentUri` would be really helpfull. I want to help. Sending a PR now. If you don't like it, you can add your own. 

Thank you for the great lib.
