### ISSUE TITLE
Example of using "join" and "where" with 3 tables

### ISSUE THREAD

**Issue by ferrannp** [SimonVT/schematic#39]
Hello!

More than an issue, I am asking for an example here... I didn't see a similar one. So let's say I have 3 tables: Shows, Seasons and Episodes. The 3 tables have a show id (Seasons and Episodes have it as a foreign key). Also, Episode has a foreign key "season" pointing to the Season table.

I want to query the table Shows where Show.state = "state_a" and then do a join so I get:

    Show.name
    Season.number
    Episode.number
    Episode.title

I saw that the @ContentUri has "where" and also "join" but I haven't really been lucky using it... 

Hope this question is ok. By the way, I saw this library announced in the Android Nanodegree by Udacity, congrats!

**Comment by MyDogTom** [comment]
Hi. Take a look at this snippet. Sorry, I haven't had time to test it, but I have quite similar code in my project.
```
    @TableEndpoint(table = DatabaseDefinition.SHOW)
    public static class ShowJoin {
        //define "virtual" columns
        public static final String SHOW_NAME = "show_name";
        public static final String SEASON_NAME = "season_name";
        public static final String EPISODE_NUMBER = "episode_number";
        public static final String EPISODE_TITLE = "episode_title";

        //projection for ContentResolver.query
        public static String[] SHOW_JOIN_PROJECTION = new String[]{SHOW_NAME, SEASON_NAME, EPISODE_NUMBER, EPISODE_NUMBER};

        @MapColumns
        public static Map<String, String> mapColumns() {
            Map<String, String> map = new HashMap<>(1);
            map.put(SHOW_NAME, DatabaseDefinition.SHOW + "." + ShowColumns.NAME);
            map.put(SEASON_NAME, DatabaseDefinition.SEASON + "." + SeasonColumns.NAME);
            map.put(EPISODE_NUMBER, DatabaseDefinition.EPISODE + "." + EpisodeColumns.NUMBER);
            map.put(EPISODE_TITLE, DatabaseDefinition.EPISODE + "." + EpisodeColumns.TITLE);
            return map;
        }

        @InexactContentUri(
                name = "SHOW_JOIN",
                path = Path.SHOW_JOIN + "/#",
                type = "vnd.example.dir/" + "show_join",
                join = "JOIN " + DatabaseDefinition.SHOW + " ON " + DatabaseDefinition.SHOW + "." + ShowColumns.ID + " = " + DatabaseDefinition.SEASON + "." + SeasonColumns.SHOW_ID
                        + " JOIN "+ DatabaseDefinition.SHOW + " ON " + DatabaseDefinition.SHOW + "." + ShowColumns.ID + " = " + DatabaseDefinition.EPISODE + "." + EpisodeColumns.SHOW_ID,
                whereColumn = ShowColumns.State,
                pathSegment = 1
        )
        public static final Uri showListWithState(String state) {
            return buildUri(Path.SHOW_JOIN, String.valueOf(state));
        }
    }
```
I pass `state` as parameter, but you should be able to hard code this and use `@ContentUri` instead of `@InexactContentUri`.
Hope it helps.

**Comment by ferrannp** [comment]
Hey, thank you very much for your answer! I'll try it and let you know. So you need to define a whole new class for this? After ``` @TableEndpoint(table = DatabaseDefinition.SHOW)``` you can define as many classes you want? I see weird using ```class``` cause I didn't see any example like that on the sample.

**Comment by MyDogTom** [comment]
>So you need to define a whole new class for this?

No. There is no need for a separate class. I just left only `join` related things for brevity. Take a look at [NotesProbider.java](https://github.com/SimonVT/schematic/blob/master/schematic-samples/src/main/java/net/simonvt/schematic/sample/database/NotesProvider.java). It has many inner classes. Each of them can have multiple `Uri` definitions. My snippet is just example of one of such `Uri` definitions. Which can be one of many others.

**Comment by ferrannp** [comment]
Well after some time I got it, and I have even more complicated stuff :). I might blog it some day cause I am doing a lot of work with this lib. Thanks for your help @MyDogTom !
