### ISSUE TITLE
Obtain db for testing

### ISSUE THREAD

**Issue by vel9** [SimonVT/schematic#42]
Hello, have really enjoyed using your generator so far! 

I'm setting up some test cases currently and have a couple of questions: what is the best way to obtain the database for testing use in an AndroidTestCase? Previously, when I wasn't using generated code, I would simply call my SomeDbHelper which extended the SQLiteOpenHelper. Is there's a similar class being generated?

Thank you
L.

**Comment by SimonVT** [comment]
The generated database has a getInstance(Context) method :)

**Comment by vel9** [comment]
Perfect, thank you.
