### ISSUE TITLE
How do we make changes to the database

### ISSUE THREAD

**Issue by chrisjeon** [SimonVT/schematic#44]
Hi,

I'm wondering how we can make changes to our database (like add/remove columns to the tables, add additional tables, and etc.)

It doesn't seem to be as simple as bumping up the `DATABASE_VERSION` number. Doing that seems to "upgrade" the database, but it doesn't make any changes to the actual database schema itself.

The github repo seems to be lacking documentation on this, and I couldn't find much on Google either. Can anyone help me out? The more I learn, I'm willing to contribute to make the documentation more solid.

**Comment by geovanisouza92** [comment]
You need to use [`@OnUpgrade`](https://github.com/SimonVT/schematic/blob/master/schematic-samples/src/main/java/net/simonvt/schematic/sample/database/NotesDatabase.java#L48) annotated method.

**Comment by chrisjeon** [comment]
@geovanisouza92 can you give an example on how we use that? Do we just declare it like that in the link? Because I tried it, and it doesn't work. It seems that we have to fill in the method some how.

**Comment by geovanisouza92** [comment]
@chrisjeon Try something like this

```java
@Database(fileName = MyDatabase.FILE_NAME, version = MyDatabase.VERSION)
public final class MyDatabase {

    public static final int VERSION = 1;
    public static final String FILE_NAME = "my.sqlite";

    public static final String[] _MIGRATIONS = {
        // Put DDL/DML commands here, one string per VERSION increment
    };

    @OnUpgrade
    public static void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        for (int i = oldVersion; i < newVersion; i++) {
            String migration = _MIGRATIONS[i - 2];
            db.beginTransaction();
            try {
                db.execSQL(migration);
                db.setTransactionSuccessful();
            } catch (Exception e) {
                Timber.e(e, "Error executing database migration: %s", migration);
                break;
            } finally {
                db.endTransaction();
            }
        }
    }
}
```

**Comment by chrisjeon** [comment]
In the comment inside `_MIGRATIONS`, what is "Put DDL/DML commands here, one string per VERSION increment" mean? Sorry, I'm pretty new to Android.

**Comment by geovanisouza92** [comment]
[DDL](https://en.wikipedia.org/wiki/Data_definition_language)/[DML](https://en.wikipedia.org/wiki/Data_manipulation_language) is just SQL. :)

**Comment by chrisjeon** [comment]
Ah, so let's say I have 3 sql statements that I would like to run, I would have to bump up the version number by 3?

**Comment by geovanisouza92** [comment]
You could use DML (`CREATE TABLE`, `ALTER TABLE`) or DML (`INSERT`, `UPDATE`, `DELETE`) to modify your db.

Upgrade to `4`, because `1` is the first version, and you are applying 3 statements. With the example code that I put above, if you set `VERSION` to 3, the last command will not be applied.

**Comment by chrisjeon** [comment]
Thanks dude, when I get the time, I'll do a PR of updated README.md with better documentation.
