### ISSUE TITLE
New user, Feature Requests

### ISSUE THREAD

**Issue by spark85** [SimonVT/schematic#47]
Hi, 

First off I want to thank you for creating this library.  I think it's awesome.  I had a few questions about it though. 

1)  Can you use a secured SQLite Database like SQLCipher? 
2)  If you want to make the ContentProvider exportable, and would like to create custom intent handling, how & where would you go about doing it? 

Thank you, 
David

**Comment by SimonVT** [comment]
1) Schematic uses Androids `SQLiteOpenHelper`. I'm not opposed to letting users back the `ContentProvider` with other databases, but I'm not sure how the API would look, and it's not something I'll be spending any time on.

2) I assume you mean `Uri`, not `Intent`. ContentProviders don't handle intents. You can subclass the generated `ContentProvider` and handle them however you'd like.
