### ISSUE TITLE
which module of this repo should be used to check sample of schematic library implementation? 

### ISSUE THREAD

**Issue by MangeshKadam** [SimonVT/schematic#50]

**Comment by SimonVT** [comment]
All of them.
It's a gradle project, just open it in AS and build.

**Comment by MangeshKadam** [comment]
I tried the same in AS and took huge amount of time for building and finally I have to force close the project.

**Comment by SimonVT** [comment]
Well, command line works. Can't really help you with AS issues. Make sure you're using the latest stable.
