### ISSUE TITLE
Writing complex sql query 

### ISSUE THREAD

**Issue by vsvankhede** [SimonVT/schematic#52]
My android application contains some complex (normalized) database structure. 
I didn't found any example which show case how one can use your library for such complex query. 
Can you please provide/guide me an example for query like shown as below? 

Ex: 
```
SELECT * from Place 
LEFT JOIN Itinerary 
ON Itinerary.place_id = Place.place_id 
AND Itinerary.trip_id='domtrip001';
```

**Comment by vsvankhede** [comment]
Found the solution after looking into SelectionBuilder.java file.

**Comment by vsvankhede** [comment]
Updated SQL query.

**Comment by SimonVT** [comment]
`@ContentUri` and `@InexactContentUri` has a `join` parameter you can use for static joins.

If part of the join statement changes, annotate a method with `@Join` and it'll be called for every query.
```java
@Join(path = "mypath")
public static String[] dynamicJoin() {
  return new String[] {
      "LEFT JOIN Itinerary ON ...",
  };
}
```
