### ISSUE TITLE
Drop Table Functionallity

### ISSUE THREAD

**Issue by sprengerst** [SimonVT/schematic#53]
Not sure if I just have overseen the functionallity. I have never seen a option to drop a table (to a.e. reset the autoincrement index).

**Comment by SimonVT** [comment]
You can do that yourself in [onUpgrade](https://github.com/SimonVT/schematic/blob/4d5e07169c86324fb6c5cbafe846cf8a6b6f33fe/schematic-annotations/src/main/java/net/simonvt/schematic/annotation/OnUpgrade.java).

**Comment by sprengerst** [comment]
How could a call on the onCreate of a @Database look like?

Also a big thanks to you, your work is a huge benifit for the whole Android community.

**Comment by SimonVT** [comment]
Schematic just generates a `SQLiteOpenHelper`. When you annotate a method with `@OnUpgrade`, it will be called by `SQLiteOpenHelper#onUpgrade` in the generated class. This gives you a `SQLiteDatabase` that you can use how you usually would.

I recommend you read up on how to use `SQLiteOpenHelper` and `SQLiteDatabase` on Android, as nothing you do in `onUpgrade` is specific to Schematic.
