### ISSUE TITLE
Content provider with multiple parameters and Adding where clauses

### ISSUE THREAD

**Issue by jdesesquelles** [SimonVT/schematic#56]
Hi guys,

  I want  to build a Uri with two parameters using schematic: 

_public static Uri withMovieIdAndSeasonNumber(String movieId, String seasonNumber) {
            return Uri.parse(**"content://" + AUTHORITY + "/show/" + movieId + "/season/" + seasonNumber**);_

   So I need to implement the following SQL request with 2 where columns :

  _Select * from seasons **where show_id = '31917' AND season_number = '7';**_

Is the following syntax correct ? It says "Attribue value must be constant" for the where clause.

        @Where(path = "show/#/season/#")
        public static String[] multipleWhere() {
            return new String[] {
                    SeasonsTable.COLUMN_SHOW_ID,
                    SeasonsTable.COLUMN_SEASON_NUMBER
            };
        }

        @InexactContentUri(
                path = "show/#/season/#",
                name = "SEASON_NUMBER",
                type = "vnd.android.cursor.item/season",
                whereColumn = multipleWhere(),  // It says Error Attribute must be constant ?
                defaultSort = SeasonsTable.COLUMN_SEASON_NUMBER + " DESC",
                pathSegment = 1)
        public static Uri withMovieIdAndSeasonNumber(String movieId, String seasonNumber) {
            return Uri.parse("content://" + AUTHORITY + "/show/" + movieId + "/season/" + seasonNumber);

Any help much appreciated

**Comment by MyDogTom** [comment]
Just use constants instead of method call. Something like this:
```
    @InexactContentUri(
            path = "show/#/season/#",
            name = "SEASON_NUMBER",
            type = "vnd.android.cursor.item/season",
            whereColumn = {SeasonsTable.COLUMN_SHOW_ID, SeasonsTable.COLUMN_SEASON_NUMBER}
            defaultSort = SeasonsTable.COLUMN_SEASON_NUMBER + " DESC",
            pathSegment = {1,3})
```

**Comment by jdesesquelles** [comment]
Excellent ! Thank you @MyDogTom.
