### ISSUE TITLE
Fails when there is a negative value in the contentURI

### ISSUE THREAD

**Issue by droidekas** [SimonVT/schematic#57]
This uri always returns a failure in updating,
`content://app.droidekas.contactsmanager.db.schematicProvider.ContactProvider/networkRequestStatuses/-50089794`,while all positive values work. I am not sure if this is a ContentProvider issue or Schematic related. Although it seems stupid ,I have tried by using positive values only and have no issues.

Can this be a problem?

Edit:

I debugged the code within  generated/ContactProvider,

in ` @Override
  public Cursor query(Uri uri, String[] projection, String selection, String[] selectionArgs, String sortOrder) `,
MATCHER.match(Uri.parse(uri.toString().replace("-",""))) matches correctly while MATCHER.match(uri) fails,

**Comment by droidekas** [comment]
This is weird ,I'm leaving it open so that you could explain why here but   
` path = Path.CONTACTS + "/*",` works while    `path = Path.CONTACTS + "/#",` does not.Am I doing something wrong here?

**Comment by SimonVT** [comment]
Seems to be `UriMatcher` only supporting positive numbers: https://code.google.com/p/android/issues/detail?id=27031
