### ISSUE TITLE
Without declaring NotifyInsert/Update/Delete, insert, update and delete operations still invoke onLoadFinished

### ISSUE THREAD

**Issue by JiaminZhu** [SimonVT/schematic#59]
I guess it's a feature rather than a bug yet I feel it's quite odd.

I find that even without declaring `@NotifyInsert`,  `@NotifyBulkInsert`,  `@NotifyUpdate` and  `@NotifyDelete` ,  the onLoadFinished (of a cursorLoader with query of certain URI) callback function still get invoked when insert, update and delete operations is performed to that URI.

I guess this is not a bug? It's just quite wired because supporting  `@NotifyInsert`,  `@NotifyBulkInsert`,  `@NotifyUpdate` and  `@NotifyDelete` somehow means that no notifying on data change without declaring these annotations.

-----

I declare the URI with
```
    public static class Quotes {
        @ContentUri(
                path = Path.QUOTES,
                type = "vnd.android.cursor.dir/quote"
        )
        public static final Uri CONTENT_URI = buildUri(Path.QUOTES);
    

      @InexactContentUri(
                name = "QUOTE_ID",
                path = Path.QUOTES + "/*",
                type = "vnd.android.cursor.item/quote",
                whereColumn = QuoteColumns.SYMBOL,
                pathSegment = 1
        )
        public static Uri withSymbol(String symbol) {
            return buildUri(Path.QUOTES, symbol);
        }
    }
```  

and query the database by defining a cursorLoader
```
        new CursorLoader(this, QuoteProvider.Quotes.CONTENT_URI,
                projection,
                selection,
                selectionArg,
                null);
```

and modify the database with
```
getContentResolver().delete(QuoteProvider.Quotes.withSymbol(symbol), null, null);
```

Then onLoadFinished gets called automatically without I declaring notifyDelete

**Comment by JiaminZhu** [comment]
or is it true that the delete insert and update operation on certain URI guarantees to notify that exact URI and cursor returned by the query of the same URI will be notified (and thus invoke onLoadFinished).


I only need to declare @NotifyInsert, @NotifyBulkInsert, @NotifyUpdate and @NotifyDelete when other URIs are also affected?

**Comment by SimonVT** [comment]
Yep, the `Uri` you use is notified by default. If you want some other behavior you use one of those annotations.

**Comment by JiaminZhu** [comment]
Thanks!!  Then can I say [this part](https://github.com/SimonVT/schematic/blob/master/schematic-samples/src/main/java/net/simonvt/schematic/sample/database/NotesProvider.java#L135-L140) of the sample code is redundant?

**Comment by SimonVT** [comment]
It's redundant, yes. Was probably added to test that it works :)

**Comment by JiaminZhu** [comment]
Thanks!!  One more question, is it true that adding the update/delete/insert annotations will notify those returned URIs **in addition** to the modified URI, right?  

It's not replacing.  It's declaring some extra uri getting notified **plus** the Uri by default.

**Comment by SimonVT** [comment]
It replaces, but nothing's stopping you from returning the same `Uri`. I'd encourage you to check out the generated code :)

**Comment by JiaminZhu** [comment]
I just did.  I guess it's [this chunk of code](https://github.com/SimonVT/schematic/blob/9ed89d2b9e620f28f4ec454943a8fa5a79a2b999/schematic-compiler/src/main/java/net/simonvt/schematic/compiler/ContentProviderWriter.java#L591-L596) did the replace job, right?  

I hope some helpful doc can be added because this @NotifyXxxxx annotations don't really explain themselves.

**Comment by SimonVT** [comment]
Yes, that's the code that generates the `ContentProvider`. You can see the class it generates in `build/generated/source/apt`.

**Comment by JiaminZhu** [comment]
Wow. I didn't know that!!!!!  This is so helpful.

btw, it's `app/build/source/apt` in my android studio
