### ISSUE TITLE
Table joins- minor issue

### ISSUE THREAD

**Issue by isdsava** [SimonVT/schematic#60]
Thank you for this project, it is excellent. Just a minor issue I had with table joins that might help others..

Notice the need to add a space " " in front of the JOIN keyword

 @ContentUri(  path = Path.SITE_PRICE_LAT_LNG,
                    type = "vnd.android.cursor.dir/site_price_lat_lng",
                    table = Path.SITE_PRICE,
                    join = _**" JOIN "**_ + BrowserDatabase.FullSites.FULL_SITES + " ON " + BrowserDatabase.SitePrice.SITE_PRICE + "." + SitePriceColumn._ID + " = " +  BrowserDatabase.FullSites.FULL_SITES + "." + FullSiteDetailsColumns._ID
       )

Otherwise when generated this statement gets mangled

case SITEPRICELATLNG_SITE_PRICE_LAT_LNG: {
        SelectionBuilder builder = getBuilder("SitePriceLatLng");
        String join = " JOIN site_price ON site_price._id = full_sites._id";
        **String table = "site_price" + join;**

Hope this makes sense

Thanks again

**Comment by SimonVT** [comment]
Update your version, this is fixed by 2b82deb :)
