### ISSUE TITLE
Add support for check, foreign key and primary key on table level.

### ISSUE THREAD

**Issue by MyDogTom** [SimonVT/schematic#65]
As suggested in #63 we can add support for other [table constraints](https://www.sqlite.org/syntax/table-constraint.html).
I can do it. But I'd like to discuss some details regarding `PrimaryKey`

1. I prefer to throw an Exception if primary key is specified multiple times (view `PrimaryKey` for column and on table level).
2. I prefer to show warning if `PrimaryKey` annotation is specified for multiple columns. Something like this: "Consider to use PrimaryKey annotation on table level".

**Comment by SimonVT** [comment]
I think an exception should be thrown. That way it's similar to how SQLite works, and there are no surprises.
