### ISSUE TITLE
Migrate from Apt to AnnotationProcessor

### ISSUE THREAD

**Issue by jatindhankhar** [SimonVT/schematic#68]
> As of the Android Gradle plugin version 2.2, all functionality that was previously provided by android-apt is now available in the Android plugin. This means that android-apt is officially obsolete ;) 
- [https://bitbucket.org/hvisser/android-apt/wiki/Migration](https://bitbucket.org/hvisser/android-apt/wiki/Migration)

Many libraries (like Butterknife) are already using annotationProcessor and if Schematic is used (which depends upon apt) with libraries which use annotationProcessor then this create issues for others that depends upon annotationProcessor.

A Migration would help 

Thanks

**Comment by SimonVT** [comment]
Does Schematic not work with `annotationProcessor`? I'm not aware of any changes I need to make to "support" `annotationProcessor`.

**Comment by jatindhankhar** [comment]
No, I tried and it works great with annotationProcessor
I mean changing the instructions on the project [REAMDE section](https://github.com/SimonVT/schematic#including-in-your-project)
where recommended way is still to apply `apply plugin: 'com.neenbedankt.android-apt'
` and then use apt `  apt 'net.simonvt.schematic:schematic-compiler:{latest-version}'
` which can just be replaced by new
`annotationProcessor 'net.simonvt.schematic:schematic-compiler:{latest-version}'`

Only issue is _id column is created twice but that's not related to annotationProcessor AFAIK
![screenshot from 2016-12-31 13-34-51](https://cloud.githubusercontent.com/assets/2412081/21576655/fc9f7f88-cf5d-11e6-834b-094cf4b7bb98.png)

For schema 

``` java
public interface UrlColumns {
    @DataType(DataType.Type.INTEGER) @PrimaryKey @AutoIncrement
      String _ID = Constants.COLUMN_ID;
    @DataType(DataType.Type.TEXT) @NotNull
     String SHORT_URL = Constants.COLUMN_SHORT_URL;
    @DataType(DataType.Type.TEXT) @NotNull
     String LONG_URL = Constants.COLUMN_LONG_URL;
    @DataType(DataType.Type.TEXT) @NotNull
     String KIND_URL = Constants.COLUMN_KIND_URL;
    @DataType(DataType.Type.TEXT) @NotNull
     String CREATED_URL = Constants.COLUMN_CREATED_DATE_URL;
    @DataType(DataType.Type.TEXT) @NotNull
     String STATUS_URL = Constants.COLUMN_STATUS_URL;
    @DataType(DataType.Type.TEXT) @NotNull
     String ANALYTICS_URL = Constants.COLUMN_ANALYTICS_URL;
}

```

**Comment by SimonVT** [comment]
Readme updated :)

**Comment by jatindhankhar** [comment]
Thank you. 
Have a great 2017 :smile:
