### ISSUE TITLE
Create dropped tables again

### ISSUE THREAD

**Issue by akashpopat** [SimonVT/schematic#74]
onUpgrade I drop tables if exist, but then how do I create the tables again ? Do I have to run the SQL commands to create table myself or if there a helper method for this ?

**Comment by SimonVT** [comment]
You can find the queries to create the tables in the generated database class, then use `SQLiteDatabase#execSql(query)`.

**Comment by akashpopat** [comment]
Can I access the generated database class and just call the exec query on that query ?

**Comment by SimonVT** [comment]
Yep :)

**Comment by akashpopat** [comment]
Thanks :) Btw this is an amazing lib 👍
