### ISSUE TITLE
java.lang.NullPointerException with no clue when using schematic 0.7.0 in SDK 26 and using annotationProcessor library.

### ISSUE THREAD

**Issue by RHMDHDYT** [SimonVT/schematic#78]
Hi. im new using this library, did i miss something? i have an issue when i build my app i've got an error message with no clue like this : 

_Error:Execution failed for task ':app:compileDebugJavaWithJavac'._
_> java.lang.NullPointerException__

I have try some example like this : https://github.com/schordas/SchematicPlanets, its worked. But, when i update the library to 0.7.0 and updating SDK version to 26 it give me a same error message.

this is my gradle :

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "com.rahmad.sampleapp"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {

    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    annotationProcessor 'net.simonvt.schematic:schematic-compiler:0.7.0'
    compile 'net.simonvt.schematic:schematic:0.7.0'
    compile 'com.google.code.gson:gson:2.8.1'
    compile 'com.android.support:appcompat-v7:26.0.1'
    compile 'com.android.support:support-v4:26.0.1'
    compile 'com.android.support:recyclerview-v7:26.0.1'
    compile 'com.android.support:design:26.0.1'
    compile 'com.facebook.stetho:stetho:1.5.0'
    testCompile 'junit:junit:4.12'
}

**Comment by SimonVT** [comment]
Make sure you're using the latest version of gradle, the android plugin, etc. You can also try and build with `--stacktrace`, see if that gives you any clues.
If you continue having issues, please create a sample project that displays the issue. Then I can take a look.

**Comment by RHMDHDYT** [comment]
here my sample app @SimonVT https://github.com/RHMDHDYT/Baking-App

**Comment by RHMDHDYT** [comment]
here from --stacktrace : 

What went wrong:
Task 'compileDebug' is ambiguous in root project 'BakingApp'. Candidates are: 'compileDebugAidl', 'compileDebugAndroidTestAidl', 'compileDebugAndroidTestJavaWithJavac', 'compileDebugAndroidTestNdk', 'compileDebugAndroidTestRenderscript', 'compileDebugAndroidTestShaders', 'compileDebugAndroidTestSources', 'compileDebugJavaWithJavac', 'compileDebugNdk', 'compileDebugRenderscript', 'compileDebugShaders', 'compileDebugSources', 'compileDebugUnitTestJavaWithJavac', 'compileDebugUnitTestSources'.

it's only happen when i use 
annotationProcessor 'net.simonvt.schematic:schematic-compiler:0.7.0'

**Comment by SimonVT** [comment]
You're missing a `@Database` annotation on `BakingDatabase`. I'll add a better error message.

**Comment by RHMDHDYT** [comment]
Oh, My bad. Thanks for responding me @SimonVT
