### ISSUE TITLE
When is onupgrade called in database

### ISSUE THREAD

**Issue by nikhil-31** [SimonVT/schematic#79]
Hi, I have been using schematic in my project and it doesnt seem to upgrade the database properly all the time and i get database errors.

```java
 public static final String[] _MIGRATIONS = {
            "//SQLite commads here",
            "//SQLite commads here"
    };

    @OnUpgrade
    public static void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        for (int i = oldVersion; i < newVersion; i++) {
            String migration = _MIGRATIONS[newVersion - oldVersion - 1];
            db.beginTransaction();
            try {
                db.execSQL(migration);
                db.setTransactionSuccessful();
            } catch (Exception e) {
                Timber.e(e, "Error executing database migration: %s", migration);
                break;
            } finally {
                db.endTransaction();
            }
        }
    }
```
OnUpgrade is not even called when the app is updated and inserts or deletes are seen as Runtime errors and the app closes, it works in debug mode

**Comment by SimonVT** [comment]
`SQLiteOpenHelper#onUpgrade` calls through to your annotated method when you bump the database version.
You can check this by viewing the source for the generated class.

**Comment by nikhil-31** [comment]
Hi, the problem was in the for loop in onUpgrade. I wrongly assumed that newVersion would give me the highest version of the database. The new version refers to the oldVersion + 1.
 ```java
public static final String[] _MIGRATIONS = {
            "//SQLite commads here",
            "//SQLite commads here"
    };

String migration = _MIGRATIONS[newVersion - oldVersion - 1];
```
Because of this, Only the 0th index SQLite command was running.
Thank you for your time and creating an amazing library.
