### ISSUE TITLE
@InexactContentUri with String value

### ISSUE THREAD

**Issue by pascalito007** [SimonVT/schematic#85]
Dear All,

I define below Uri inside my Provider

 @InexactContentUri(
                path = "podcasts" + "/#",
                name = "LIST_ID",
                type = "vnd.android.cursor.item/podcasts",
                whereColumn = PodcastContract.COLUMN_PODCAST_ID_2,
                pathSegment = 1)
        public static Uri withProvider(String tag) {
            return Uri.parse("content://" + AUTORITY + "/podcasts/" + tag);
        }

The tag values can be: **gpodder.net** or **itunes** or **other tag** 

My problem is that I got unknown URI exception when passing String values but When I replace the parameter with Integer value its work well. How can I provide String value in parameter and got my Uri works ?
Thks

**Comment by SimonVT** [comment]
I think you need to use `podcasts/*` instead. Schematic uses `UriMatcher` behind the scenes, try reading up on that if my suggestion doesn't work :)

**Comment by pascalito007** [comment]
Thank You very much @SimonVT  For your answer. Please where do I need to change **podcasts/*** ?

**Comment by SimonVT** [comment]
Instead if `podcasts/#` in your path. Afaik `#` is just for numbers.

**Comment by pascalito007** [comment]
Its working like a charm @SimonVT  Thanks a lot but I face same issue for insert. When I make insert for exemple
[context.getContentResolver().insert(CategoryProvider.CategoryList.CONTENT_URI, cv);](url)
I got the same exception
[java.lang.IllegalArgumentException: Unknown URI content://capstone.nanodegree.udacity.com.mypodcast.categoryprovider/categories/information](url)
Below My Provider
[@ContentUri(
                path = "categories",
                type = "vnd.android.cursor.dir/categories"
        )
        public static final Uri CONTENT_URI = Uri.parse("content://" + AUTORITY + "/categories");](url)

**Comment by pascalito007** [comment]
Everything is OK @SimonVT  . All works like a charm. Thanks a lot
